// project/src/components/layout/Header.tsx
import React from 'react';
import { Bell, Menu, Search, Settings, X } from 'lucide-react';
import { Avatar } from '../common/Avatar';
import { Button } from '../common/Button';
import { useTheme } from '../../contexts/ThemeContext';
import { cn } from '../../lib/utils';

type HeaderProps = {
  setSidebarOpen: (open: boolean) => void;
};

export function Header({ setSidebarOpen }: HeaderProps) {
  const { theme, toggleTheme } = useTheme();
  const [showSearch, setShowSearch] = React.useState(false);

  return (
    <header className="sticky top-0 z-30 flex h-16 items-center gap-x-4 border-b bg-background px-4 sm:px-6 lg:px-8">
      <Button
        variant="ghost"
        size="icon"
        className="lg:hidden"
        onClick={() => setSidebarOpen(true)}
      >
        <Menu className="h-6 w-6" />
        <span className="sr-only">Open sidebar</span>
      </Button>

      <div className="flex flex-1 items-center justify-between">
        <div
          className={cn(
            'hidden transition-all duration-300 ease-in-out lg:block',
            showSearch ? 'lg:hidden' : 'lg:block'
          )}
        >
          <h1 className="text-xl font-semibold">Task Manager</h1>
        </div>

        <div className="flex items-center gap-x-4 lg:gap-x-6">
          <div
            className={cn(
              'relative transition-all duration-300 ease-in-out',
              showSearch ? 'w-full' : 'w-40 lg:w-64'
            )}
          >
            <div
              className={cn(
                'absolute inset-y-0 left-0 flex items-center pl-3',
                showSearch ? 'block' : 'hidden lg:block'
              )}
            >
              <Search className="h-4 w-4 text-muted-foreground" />
            </div>
            <input
              type="search"
              placeholder="Search..."
              className={cn(
                'w-full rounded-md border border-input bg-background py-2 text-sm transition-all duration-300 ease-in-out',
                showSearch
                  ? 'pl-10 pr-10'
                  : 'pl-10 hidden lg:block'
              )}
            />
            <div
              className={cn(
                'absolute inset-y-0 right-0 flex items-center pr-3',
                showSearch ? 'block' : 'hidden'
              )}
            >
              <Button
                variant="ghost"
                size="icon"
                className="h-5 w-5"
                onClick={() => setShowSearch(false)}
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>

          <Button
            variant="ghost"
            size="icon"
            className="lg:hidden"
            onClick={() => setShowSearch(true)}
          >
            <Search className="h-5 w-5" />
          </Button>

          <Button
            variant="ghost"
            size="icon"
            onClick={toggleTheme}
            className="hover:bg-transparent"
          >
            {theme === 'light' ? (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="h-5 w-5"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M21.752 15.002A9.718 9.718 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z"
                />
              </svg>
            ) : (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="h-5 w-5"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                />
              </svg>
            )}
          </Button>

          <Button variant="ghost" size="icon" className="relative">
            <Bell className="h-5 w-5" />
            <span className="absolute right-1 top-1 flex h-2 w-2">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-error opacity-75"></span>
              <span className="relative inline-flex h-2 w-2 rounded-full bg-error"></span>
            </span>
          </Button>

          <Button variant="ghost" size="icon">
            <Settings className="h-5 w-5" />
          </Button>

          <div className="relative">
            <Avatar
              src="https://i.pravatar.cc/150?img=1"
              alt="User"
              name="Alex Johnson"
              size="sm"
            />
          </div>
        </div>
      </div>
    </header>
  );
}

// frontend/src/app/layout/header/header.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <header class="sticky top-0 z-30 flex h-16 items-center gap-x-4 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 px-4 sm:px-6 lg:px-8">
      <button
        class="lg:hidden -m-2.5 p-2.5 text-muted-foreground hover:text-foreground transition-colors"
        (click)="sidebarOpenChange.emit(true)"
      >
        <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
        <span class="sr-only">Open sidebar</span>
      </button>

      <nav class="flex flex-1 items-center justify-between">
        <section class="hidden lg:block">
          <h1 class="text-xl font-semibold tracking-tight">Task Manager</h1>
        </section>

        <section class="flex items-center gap-x-4 lg:gap-x-6">
          <form class="relative w-40 lg:w-64">
            <label class="absolute inset-y-0 left-0 flex items-center pl-3">
              <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </label>
            <input
              type="search"
              placeholder="Search..."
              class="w-full rounded-md border border-input bg-background py-2 pl-10 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            />
          </form>

          <button class="lg:hidden text-muted-foreground hover:text-foreground transition-colors">
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </button>

          <button class="text-muted-foreground hover:text-foreground transition-colors">
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" />
            </svg>
          </button>

          <button class="relative text-muted-foreground hover:text-foreground transition-colors">
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
            </svg>
            <mark class="absolute right-1 top-1 flex h-2 w-2">
              <mark class="absolute inline-flex h-full w-full animate-ping rounded-full bg-error opacity-75"></mark>
              <mark class="relative inline-flex h-2 w-2 rounded-full bg-error"></mark>
            </mark>
          </button>

          <button class="text-muted-foreground hover:text-foreground transition-colors">
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
          </button>

          <figure class="relative">
            <figure class="h-8 w-8 rounded-full bg-primary flex items-center justify-center text-primary-foreground font-medium">
              AJ
            </figure>
          </figure>
        </section>
      </nav>
    </header>
  `,
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class HeaderComponent {
  @Output() sidebarOpenChange = new EventEmitter<boolean>();
} 
<header class="sticky top-0 z-30 flex h-16 items-center gap-x-4 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 px-4 sm:px-6 lg:px-8">
  <!-- Mobile menu button -->
  <button
    class="lg:hidden -m-2.5 p-2.5 text-muted-foreground hover:text-foreground transition-colors rounded-lg hover:bg-muted/50"
    (click)="sidebarOpenChange.emit(true)"
  >
    <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
    </svg>
    <span class="sr-only">Open sidebar</span>
  </button>

  <nav class="flex flex-1 items-center justify-between">
    <!-- Title -->
    <section class="hidden lg:flex items-center gap-3">
      <figure class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary shadow-sm">
        <svg class="h-5 w-5 text-primary-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
        </svg>
      </figure>
      <h1 class="text-xl font-semibold tracking-tight">Task Manager</h1>
    </section>

    <!-- Actions -->
    <section class="flex items-center gap-x-2 lg:gap-x-4">
      <!-- Search -->
      <form class="relative hidden sm:block">
        <label class="absolute inset-y-0 left-0 flex items-center pl-3">
          <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
        </label>
        <input
          type="search"
          placeholder="Search tasks, teams..."
          class="w-40 rounded-lg border border-input bg-background py-2 pl-10 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring lg:w-64 transition-all duration-200"
        />
      </form>

      <!-- Mobile search button -->
      <button class="sm:hidden text-muted-foreground hover:text-foreground transition-colors rounded-lg p-2 hover:bg-muted/50">
        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
      </button>

      <!-- Theme toggle -->
      <button class="text-muted-foreground hover:text-foreground transition-colors rounded-lg p-2 hover:bg-muted/50">
        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" />
        </svg>
      </button>

      <!-- Notifications -->
      <button class="relative text-muted-foreground hover:text-foreground transition-colors rounded-lg p-2 hover:bg-muted/50">
        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
        </svg>
        <span class="absolute right-1 top-1 flex h-2 w-2">
          <span class="absolute inline-flex h-full w-full animate-ping rounded-full bg-error opacity-75"></span>
          <span class="relative inline-flex h-2 w-2 rounded-full bg-error"></span>
        </span>
      </button>

      <!-- Settings -->
      <button class="text-muted-foreground hover:text-foreground transition-colors rounded-lg p-2 hover:bg-muted/50">
        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
      </button>

      <!-- Profile -->
      <div class="relative">
        <button class="flex items-center gap-2 rounded-lg px-2 py-1.5 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted/50 hover:text-foreground">
          <figure class="h-8 w-8 rounded-full bg-primary flex items-center justify-center text-primary-foreground font-medium shadow-sm">
            AJ
          </figure>
          <span class="hidden lg:inline-block">Alex Johnson</span>
          <svg class="h-4 w-4 hidden lg:block" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </button>
      </div>
    </section>
  </nav>
</header>
