// project/src/components/layout/Sidebar.tsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { cn } from '../../lib/utils';
import {
  BarChart3,
  Users,
  UserCircle,
  CheckSquare,
  Settings,
  HelpCircle,
  X,
} from 'lucide-react';
import { Button } from '../common/Button';

type SidebarProps = {
  sidebarOpen: boolean;
  setSidebarOpen: (open: boolean) => void;
};

export function Sidebar({ sidebarOpen, setSidebarOpen }: SidebarProps) {
  const location = useLocation();

  const navigation = [
    { name: 'Dashboard', href: '/', icon: BarChart3 },
    { name: 'Teams', href: '/teams', icon: Users },
    { name: 'Users', href: '/users', icon: UserCircle },
    { name: 'Tasks', href: '/tasks', icon: CheckSquare },
    { name: 'Settings', href: '/settings', icon: Settings },
  ];

  return (
    <>
      <div
        className={cn(
          'fixed inset-0 z-40 bg-background/80 backdrop-blur-sm transition-opacity duration-300 lg:hidden',
          sidebarOpen ? 'opacity-100' : 'pointer-events-none opacity-0'
        )}
        onClick={() => setSidebarOpen(false)}
      />

      <div
        className={cn(
          'fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-card transition-transform duration-300 lg:z-auto lg:translate-x-0',
          sidebarOpen ? 'translate-x-0' : '-translate-x-full'
        )}
      >
        <div className="flex h-16 items-center justify-between border-b px-4">
          <div className="flex items-center">
            <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary">
              <CheckSquare className="h-5 w-5 text-primary-foreground" />
            </div>
            <span className="ml-3 text-lg font-semibold">TaskManager</span>
          </div>
          <Button
            variant="ghost"
            size="icon"
            className="lg:hidden"
            onClick={() => setSidebarOpen(false)}
          >
            <X className="h-6 w-6" />
          </Button>
        </div>

        <div className="flex-1 overflow-y-auto py-4">
          <nav className="space-y-1 px-2">
            {navigation.map((item) => {
              const isActive = location.pathname === item.href;
              return (
                <Link
                  key={item.name}
                  to={item.href}
                  className={cn(
                    'group flex items-center rounded-md px-3 py-2 text-sm font-medium transition-colors',
                    isActive
                      ? 'bg-primary/10 text-primary'
                      : 'text-foreground hover:bg-muted'
                  )}
                >
                  <item.icon
                    className={cn(
                      'mr-3 h-5 w-5 flex-shrink-0',
                      isActive
                        ? 'text-primary'
                        : 'text-muted-foreground group-hover:text-foreground'
                    )}
                  />
                  {item.name}
                </Link>
              );
            })}
          </nav>
        </div>

        <div className="border-t p-4">
          <div className="flex items-center">
            <HelpCircle className="h-5 w-5 text-muted-foreground" />
            <span className="ml-3 text-sm font-medium">Help & Support</span>
          </div>
        </div>
      </div>
    </>
  );
}

// frontend/src/app/layout/sidebar/sidebar.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent {
  @Input() sidebarOpen = false;
  @Output() sidebarOpenChange = new EventEmitter<boolean>();

  isActive(path: string): boolean {
    return window.location.pathname === path;
  }
} 
<aside
  class="fixed inset-0 z-40 bg-background/80 backdrop-blur-sm transition-opacity duration-300 lg:hidden"
  [class.opacity-100]="sidebarOpen"
  [class.pointer-events-none]="!sidebarOpen"
  [class.opacity-0]="!sidebarOpen"
  (click)="sidebarOpenChange.emit(false)"
></aside>

<aside
  class="fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-card transition-transform duration-300 lg:z-auto lg:translate-x-0"
  [class.translate-x-0]="sidebarOpen"
  [class.-translate-x-full]="!sidebarOpen"
>
  <header class="flex h-16 items-center justify-between border-b px-4">
    <figure class="flex items-center">
      <figure class="flex h-8 w-8 items-center justify-center rounded-md bg-primary">
        <svg class="h-5 w-5 text-primary-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
        </svg>
      </figure>
      <h1 class="ml-3 text-lg font-semibold tracking-tight">TaskManager</h1>
    </figure>
    <button
      class="lg:hidden -m-2.5 p-2.5 text-muted-foreground hover:text-foreground transition-colors"
      (click)="sidebarOpenChange.emit(false)"
    >
      <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </header>

  <nav class="flex-1 overflow-y-auto py-4">
    <ul class="space-y-1 px-2">
      <li>
        <a
          routerLink="/"
          routerLinkActive="bg-primary/10 text-primary"
          [routerLinkActiveOptions]="{ exact: true }"
          class="group flex items-center rounded-md px-3 py-2 text-sm font-medium transition-colors"
          [class.text-foreground]="!isActive('/')"
          [class.hover:bg-muted]="!isActive('/')"
        >
          <svg class="mr-3 h-5 w-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
          </svg>
          Dashboard
        </a>
      </li>

      <li>
        <a
          routerLink="/teams"
          routerLinkActive="bg-primary/10 text-primary"
          class="group flex items-center rounded-md px-3 py-2 text-sm font-medium transition-colors"
          [class.text-foreground]="!isActive('/teams')"
          [class.hover:bg-muted]="!isActive('/teams')"
        >
          <svg class="mr-3 h-5 w-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
          </svg>
          Teams
        </a>
      </li>

      <li>
        <a
          routerLink="/tasks"
          routerLinkActive="bg-primary/10 text-primary"
          class="group flex items-center rounded-md px-3 py-2 text-sm font-medium transition-colors"
          [class.text-foreground]="!isActive('/tasks')"
          [class.hover:bg-muted]="!isActive('/tasks')"
        >
          <svg class="mr-3 h-5 w-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
          </svg>
          Tasks
        </a>
      </li>

      <li>
        <a
          routerLink="/settings"
          routerLinkActive="bg-primary/10 text-primary"
          class="group flex items-center rounded-md px-3 py-2 text-sm font-medium transition-colors"
          [class.text-foreground]="!isActive('/settings')"
          [class.hover:bg-muted]="!isActive('/settings')"
        >
          <svg class="mr-3 h-5 w-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          Settings
        </a>
      </li>
    </ul>
  </nav>

  <footer class="border-t p-4">
    <figure class="flex items-center">
      <svg class="h-5 w-5 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <p class="ml-3 text-sm font-medium">Help & Support</p>
    </figure>
  </footer>
</aside>
