// frontend/src/app/dashboard/performance-chart/performance-chart.component.ts
import { Component, Input, ViewChild, ElementRef, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Chart, registerables } from 'chart.js';

Chart.register(...registerables);

@Component({
  selector: 'app-performance-chart',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="h-[400px]">
      <canvas #performanceChart></canvas>
    </div>
  `,
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class PerformanceChartComponent implements AfterViewInit {
  @ViewChild('performanceChart') chartRef!: ElementRef<HTMLCanvasElement>;
  @Input() teamPerformance: { team: string; performance: number }[] = [];

  private chart: Chart | null = null;

  ngAfterViewInit() {
    this.createChart();
  }

  private createChart() {
    const ctx = this.chartRef.nativeElement.getContext('2d');
    if (!ctx) return;

    const data = {
      labels: this.teamPerformance.map(item => item.team),
      datasets: [{
        label: 'Team Performance',
        data: this.teamPerformance.map(item => item.performance),
        backgroundColor: 'rgba(59, 130, 246, 0.5)',
        borderColor: 'rgb(59, 130, 246)',
        borderWidth: 2,
        tension: 0.4,
        fill: true
      }]
    };

    this.chart = new Chart(ctx, {
      type: 'line',
      data,
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false
          },
          tooltip: {
            backgroundColor: 'rgba(0, 0, 0, 0.8)',
            padding: 12,
            titleColor: '#fff',
            titleFont: {
              size: 14,
              weight: 'bold'
            },
            bodyColor: '#fff',
            bodyFont: {
              size: 13
            },
            borderColor: 'rgba(255, 255, 255, 0.1)',
            borderWidth: 1
          }
        },
        scales: {
          y: {
            beginAtZero: true,
            grid: {
              color: 'rgba(0, 0, 0, 0.1)'
            },
            ticks: {
              callback: (value) => `${value}%`
            }
          },
          x: {
            grid: {
              display: false
            }
          }
        }
      }
    });
  }
} 
<section class="bg-white rounded-lg shadow p-4">
  <header>
    <h2 class="text-xl font-semibold mb-4">Team Performance</h2>
  </header>
  <main class="h-64">
    <canvas #chartCanvas></canvas>
  </main>
</section>

// project/src/components/dashboard/PerformanceChart.tsx
import React from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';
import { Card, CardContent, CardHeader, CardTitle } from '../common/Card';
import { DashboardMetrics } from '../../types';
import { useTheme } from '../../contexts/ThemeContext';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

type PerformanceChartProps = {
  teamPerformance: DashboardMetrics['teamPerformance'];
};

export function PerformanceChart({ teamPerformance }: PerformanceChartProps) {
  const { theme } = useTheme();
  const isDark = theme === 'dark';

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: false,
      },
      tooltip: {
        callbacks: {
          label: function (context: any) {
            return `Completion Rate: ${context.raw}%`;
          },
        },
      },
    },
    scales: {
      x: {
        grid: {
          display: false,
          color: isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)',
        },
        ticks: {
          color: isDark ? 'rgba(255, 255, 255, 0.7)' : 'rgba(0, 0, 0, 0.7)',
        },
      },
      y: {
        beginAtZero: true,
        max: 100,
        grid: {
          color: isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)',
        },
        ticks: {
          color: isDark ? 'rgba(255, 255, 255, 0.7)' : 'rgba(0, 0, 0, 0.7)',
          callback: function (value: any) {
            return value + '%';
          },
        },
      },
    },
  };

  const data = {
    labels: teamPerformance.map((team) => team.teamName),
    datasets: [
      {
        data: teamPerformance.map((team) => team.completionRate),
        backgroundColor: [
          'rgba(79, 70, 229, 0.8)',
          'rgba(14, 165, 233, 0.8)',
          'rgba(245, 158, 11, 0.8)',
          'rgba(16, 185, 129, 0.8)',
          'rgba(249, 115, 22, 0.8)',
        ],
        borderWidth: 0,
        borderRadius: 4,
      },
    ],
  };

  return (
    <Card className="animate-in">
      <CardHeader>
        <CardTitle>Team Performance</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="h-80">
          <Bar options={options as any} data={data} />
        </div>
      </CardContent>
    </Card>
  );
}
